// metro.config.js
// Ensures native-only libraries (Stripe, react-native-maps, react-native-draggable-flatlist,
// react-native-purchases, expo-web-browser) are excluded from the web bundle by resolving
// them to no-op stubs.
//
// Six-layer defence (in order of precedence):
//   1. blockList        — prevents Stripe native spec files from being parsed
//                         AT ALL (transformer-level, before any resolver runs)
//   2. extraNodeModules — fastest path for named package-level imports on web
//   3. resolveRequest (web)    — intercepts sub-path + transitive requires on web,
//                                handles null platform (pnpm) and origin-path check
//   4. resolveRequest (native) — catches relative imports of non-existent spec
//                                files from *inside* the Stripe package on iOS/Android
//                                (NativeStripeSdkModule etc. — generated by codegen,
//                                 not present in the npm tarball itself)
//   5. Origin-path check       — covers pnpm virtual store paths using '+' separator
//   6. emptyModule proxy       — Proxy-based stub that silently absorbs all property
//                                access, function calls, and constructor invocations

const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

const config = getDefaultConfig(__dirname);

// ── Native-only top-level packages to stub on web ────────────────────────────
const NATIVE_ONLY_MODULES = [
  '@stripe/stripe-react-native',
  'react-native-maps',
  'react-native-draggable-flatlist',
  'react-native-purchases',
  'expo-web-browser',
];

// ── Specific native-only sub-module paths that must always be stubbed on web ──
const NATIVE_ONLY_SUBMODULES = [
  'react-native/Libraries/Utilities/codegenNativeCommands',
  'react-native/Libraries/Utilities/codegenNativeComponent',
  'react-native/Libraries/Components/View/NativeViewManagerAdapter',
  'react-native/Libraries/Utilities/RCTExport',
  'react-native/Libraries/TurboModule/TurboModuleRegistry',
];

// ── Stripe internal spec file name patterns (relative imports inside package) ──
// These are TurboModule spec files generated by codegen during native build.
// They do NOT exist in the npm tarball — only in a post-codegen build tree.
// We must stub them on ALL platforms when Metro tries to resolve them from
// inside the Stripe package source files.
const STRIPE_MISSING_SPEC_PATTERNS = [
  /\/specs\/NativeStripeSdkModule/,
  /\/specs\/NativeCardField/,
  /\/specs\/NativePaymentSheet/,
  /\/specs\/NativeStripeSdk/,
  /[/\\]specs[/\\]Native\w+/,
];

const STUB = require.resolve('./scripts/emptyModule.js');

// ── 1. blockList — prevent Stripe native spec files from being processed ──────
const STRIPE_SPECS_BLOCK = [
  /node_modules[/\\]\.pnpm[/\\][^/\\]*stripe[^/\\]*[/\\]node_modules[/\\]@stripe[/\\]stripe-react-native[/\\]lib[/\\]commonjs[/\\]specs[/\\]/,
  /node_modules[/\\]\.pnpm[/\\][^/\\]*stripe[^/\\]*[/\\]node_modules[/\\]@stripe[/\\]stripe-react-native[/\\]src[/\\]specs[/\\]/,
  /node_modules[/\\]@stripe[/\\]stripe-react-native[/\\]lib[/\\]commonjs[/\\]specs[/\\]/,
  /node_modules[/\\]@stripe[/\\]stripe-react-native[/\\]src[/\\]specs[/\\]/,
];

const existingBlockList = config.resolver.blockList;
config.resolver.blockList = [
  ...(existingBlockList
    ? Array.isArray(existingBlockList)
      ? existingBlockList
      : [existingBlockList]
    : []),
  ...STRIPE_SPECS_BLOCK,
];

// ── 2. extraNodeModules — fastest path for top-level named imports ────────────
config.resolver.extraNodeModules = {
  ...(config.resolver.extraNodeModules ?? {}),
  ...Object.fromEntries(NATIVE_ONLY_MODULES.map((mod) => [mod, STUB])),
  ...Object.fromEntries(NATIVE_ONLY_SUBMODULES.map((mod) => [mod, STUB])),
};

// ── Allow .mjs files ──────────────────────────────────────────────────────────
config.resolver.sourceExts = [
  ...new Set([...(config.resolver.sourceExts ?? []), 'mjs']),
];

// ── Origin-path regexes — covers BOTH npm flat AND pnpm virtual store ─────────
const NATIVE_ONLY_ORIGIN_REGEXPS = [
  /node_modules[/\\]\.pnpm[/\\][^/\\]*stripe[^/\\]*/i,
  /node_modules[/\\]@stripe[/\\]stripe-react-native[/\\]/i,
  /node_modules[/\\]react-native-maps[/\\]/i,
  /node_modules[/\\]react-native-draggable-flatlist[/\\]/i,
  /node_modules[/\\]react-native-purchases[/\\]/i,
  /node_modules[/\\]expo-web-browser[/\\]/i,
];

function isFromNativeOnlyPkg(originPath) {
  if (!originPath || typeof originPath !== 'string') return false;
  return NATIVE_ONLY_ORIGIN_REGEXPS.some((re) => re.test(originPath));
}

function isNativeOnlyModule(moduleName) {
  if (!moduleName || typeof moduleName !== 'string') return false;
  for (const mod of NATIVE_ONLY_MODULES) {
    if (moduleName === mod || moduleName.startsWith(mod + '/')) return true;
  }
  for (const sub of NATIVE_ONLY_SUBMODULES) {
    if (moduleName === sub || moduleName.startsWith(sub + '/')) return true;
  }
  return false;
}

// ── Is this a missing Stripe codegen spec file (relative import)? ─────────────
// These files are generated during `pod install` / `gradle sync` and only
// exist in a post-codegen native build. They are NEVER in the npm tarball.
// We must stub them on ALL platforms when imported from inside the package.
function isStripeSpecRelativeImport(moduleName, originPath) {
  if (!moduleName || typeof moduleName !== 'string') return false;
  // Only apply when the import originates from inside the Stripe package
  if (!isFromNativeOnlyPkg(originPath ?? '')) return false;
  return STRIPE_MISSING_SPEC_PATTERNS.some((re) => re.test(moduleName));
}

// ── 3, 4 & 5. resolveRequest ──────────────────────────────────────────────────
const originalResolver = config.resolver.resolveRequest;

config.resolver.resolveRequest = (context, moduleName, platform) => {
  const isWeb = platform === 'web' || platform == null;
  const originPath = context.originModulePath ?? '';

  // ── Layer 4 (ALL platforms): stub missing Stripe codegen spec files ──────────
  // This fires for both iOS and Android when Metro tries to resolve relative
  // imports like '../specs/NativeStripeSdkModule' from inside StripeProvider.tsx.
  // These files don't exist in the npm tarball — they're generated by codegen.
  if (isStripeSpecRelativeImport(moduleName, originPath)) {
    return { filePath: STUB, type: 'sourceFile' };
  }

  // ── Layer 5 (ALL platforms): any require from inside Stripe src/specs/ ───────
  // Belt-and-braces: if the origin is the specs dir itself (shouldn't happen
  // after blockList) redirect everything to the stub.
  if (
    originPath &&
    /[/\\]stripe-react-native[/\\]src[/\\]specs[/\\]/.test(originPath)
  ) {
    return { filePath: STUB, type: 'sourceFile' };
  }

  if (isWeb) {
    // Layer 3a: direct named import of a blocked package or known native sub-path
    if (isNativeOnlyModule(moduleName)) {
      return { filePath: STUB, type: 'sourceFile' };
    }

    // Layer 3b: transitive require originating from inside a blocked package
    if (isFromNativeOnlyPkg(originPath)) {
      return { filePath: STUB, type: 'sourceFile' };
    }
  }

  // Fall through to the default resolver
  if (originalResolver) {
    return originalResolver(context, moduleName, platform);
  }
  return context.resolveRequest(context, moduleName, platform);
};

module.exports = config;
